CLASS_NAMES = [
    "Hair Pulling",
    "Nail Biting",
    "Nose Picking",
    "Thumb Sucking",
    "Eyeglasses",
    "Knuckle Cracking",
    "Face Touching",
    "Leg Shaking",
    "Scratching Arm",
    "Cuticle Picking",
    "Leg Scratching",
    "Phone Call",
    "Eating",
    "Drinking",
    "Stretching",
    "Hand Waving",
    "Reading",
    "Using Phone",
    "Standing",
    "Sit-to-Stand",
    "Stand-to-Sit",
    "Walking",
    "Sitting Still",
    "Raising Hand",
]
